name: files2tiles
channels:
  - conda-forge
dependencies:
  - pip
  - gdal>=3.5.0
  - proj>=9.0.0
  - numpy>=1.22.4
  - python>=3.6.10
  - rasterio>=1.2.10
  - fiona>=1.8.21
  - shapely>=1.8.2
  - pycrs>=1.0.2
